export const notifications = [
  { id: 1, type: 'application', title: 'Fresh AI match', message: 'Nisha Rao crossed 95% relevance for ML Engineer.', time: '8 min ago', unread: true },
  { id: 2, type: 'success', title: 'Interview accepted', message: 'Daniel Kim accepted the Product Designer interview slot.', time: '1 hour ago', unread: true },
  { id: 3, type: 'job', title: 'Talent pool refreshed', message: '18 new backend profiles were added to your saved pool.', time: 'Today', unread: false },
];

export const candidateData = [
  {
    id: 1,
    name: 'Nisha Rao',
    role: 'Machine Learning Engineer',
    stage: 'Shortlisted',
    score: 96,
    experience: '4 years',
    location: 'Bengaluru, India',
    availability: 'Immediate',
    salary: '$42k expected',
    lastActive: '2 hours ago',
    email: 'nisha.rao@talentpulse.ai',
    phone: '+91 98765 11223',
    education: 'M.Tech, Artificial Intelligence',
    skills: ['Python', 'PyTorch', 'MLOps', 'NLP'],
    strengths: ['Production ML pipelines', 'Fast experimentation', 'Strong communication'],
    insight: 'Strong overlap with your ML Engineer posting and above-average shipping velocity.',
  },
  {
    id: 2,
    name: 'Daniel Kim',
    role: 'Product Designer',
    stage: 'Interviewing',
    score: 91,
    experience: '6 years',
    location: 'Remote',
    availability: '2 weeks',
    salary: '$78/hr expected',
    lastActive: '35 min ago',
    email: 'daniel.kim@talentpulse.ai',
    phone: '+1 415 555 0194',
    education: 'B.Des, Human Centered Design',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping'],
    strengths: ['Design leadership', 'Senior stakeholder alignment', 'Fast prototyping'],
    insight: 'Excellent portfolio depth and high alignment with design-system heavy roles.',
  },
  {
    id: 3,
    name: 'Arjun Mehta',
    role: 'Senior Backend Engineer',
    stage: 'Screening',
    score: 89,
    experience: '5 years',
    location: 'Hyderabad, India',
    availability: '30 days',
    salary: '$48k expected',
    lastActive: 'Today',
    email: 'arjun.mehta@talentpulse.ai',
    phone: '+91 98220 55441',
    education: 'B.Tech, Computer Science',
    skills: ['FastAPI', 'PostgreSQL', 'Redis', 'AWS'],
    strengths: ['API architecture', 'Database tuning', 'Reliability mindset'],
    insight: 'Backend depth is strong; AI flagged this candidate as reliable for scaling teams.',
  },
  {
    id: 4,
    name: 'Sara Iqbal',
    role: 'Full Stack Developer',
    stage: 'Applied',
    score: 86,
    experience: '3 years',
    location: 'Lahore, Pakistan',
    availability: 'Immediate',
    salary: '$36k expected',
    lastActive: '1 day ago',
    email: 'sara.iqbal@talentpulse.ai',
    phone: '+92 321 555 8876',
    education: 'BS, Software Engineering',
    skills: ['React', 'Node.js', 'MongoDB', 'TypeScript'],
    strengths: ['Fast delivery', 'Clean UI implementation', 'Startup adaptability'],
    insight: 'Good end-to-end breadth; best suited for fast-moving product squads.',
  },
  {
    id: 5,
    name: 'Marcus Wright',
    role: 'DevOps Engineer',
    stage: 'Saved',
    score: 84,
    experience: '7 years',
    location: 'Austin, TX',
    availability: '2 weeks',
    salary: '$145k expected',
    lastActive: '3 hours ago',
    email: 'marcus.wright@talentpulse.ai',
    phone: '+1 512 555 0138',
    education: 'MS, Systems Engineering',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD'],
    strengths: ['Infra automation', 'Security posture', 'Incident response'],
    insight: 'Best match for infrastructure-heavy roles with ownership expectations.',
  },
  {
    id: 6,
    name: 'Priya Menon',
    role: 'Data Scientist',
    stage: 'Shortlisted',
    score: 93,
    experience: '4.5 years',
    location: 'Mumbai, India',
    availability: '15 days',
    salary: '$40k expected',
    lastActive: '10 min ago',
    email: 'priya.menon@talentpulse.ai',
    phone: '+91 98110 77764',
    education: 'MSc, Data Science',
    skills: ['Python', 'TensorFlow', 'SQL', 'Experimentation'],
    strengths: ['Model evaluation', 'Business storytelling', 'High ownership'],
    insight: 'Strong fit for product analytics plus ML experimentation roles.',
  },
];

export const stageOptions = ['all', 'Applied', 'Screening', 'Shortlisted', 'Interviewing', 'Saved'];

export const getCandidateById = (candidateId) => {
  const parsedId = Number(candidateId);
  return candidateData.find((candidate) => candidate.id === parsedId);
};
